//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int BasketID { get; set; }
        public string BarcodNo { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal TotalPrice { get; set; }
        public int Tax { get; set; }
        public int UnitID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Basket Basket { get; set; }
    }
}
